### ISSUE TITLE
Pro

### ISSUE THREAD

**Issue by vivianxhh** [Cryptum169/textCNN-for-Chinese#2]
Dear Sir:
   Where to find my_dict.json and keras_model/model_doc2vec.hdf5 from predict_keras_doc2vec.py?
yours sinerely,
Huihui Xiao

**Comment by Cryptum169** [comment]
Unfortunately the data were of proprietary nature and it wouldn't be possible to share them. You can certainly train your own `doc2vec` model since, iirc, it should be a unsupervised method. At the time, Sougo would be a starting place to start looking for good datasets, in terms of both size and quality. I have unfortunately not touched NLP since then so there might be a better alternative of datasets now.
